#!/bin/bash
# =============================================================================
# setup-audit.sh - Auditd Setup for NurOS Container Security
# =============================================================================
# This script configures auditd to log AppArmor denials and security events
# for the container-nuros-strict profile.
#
# Usage:
#   sudo ./setup-audit.sh
#
# Requirements:
#   - Linux with auditd installed
#   - Root/sudo privileges
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Check if auditd is installed
check_auditd_installed() {
    log_info "Checking if auditd is installed..."
    
    if command -v auditctl &> /dev/null; then
        log_success "auditd is installed"
        return 0
    else
        log_error "auditd is not installed"
        return 1
    fi
}

# Install auditd if not installed
install_auditd() {
    log_info "Installing auditd..."
    
    if [ -f /etc/debian_version ]; then
        # Debian/Ubuntu
        apt update
        apt install -y auditd
    elif [ -f /etc/redhat-release ]; then
        # RHEL/CentOS/Fedora
        yum install -y audit
    else
        log_error "Unsupported distribution. Please install auditd manually."
        exit 1
    fi
    
    log_success "auditd installed"
}

# Start and enable auditd service
start_auditd() {
    log_info "Starting auditd service..."
    
    systemctl enable auditd
    systemctl start auditd
    
    if systemctl is-active --quiet auditd; then
        log_success "auditd is running"
    else
        log_error "Failed to start auditd"
        exit 1
    fi
}

# Configure audit rules for AppArmor
configure_audit_rules() {
    log_info "Configuring audit rules for AppArmor..."
    
    # Add runtime rules
    auditctl -w /sys/kernel/apparmor -p rwa -k apparmor 2>/dev/null || \
        log_warning "Could not add rule for /sys/kernel/apparmor"
    
    auditctl -w /etc/apparmor.d/container-nuros-strict -p rwa -k apparmor_profile 2>/dev/null || \
        log_warning "Could not add rule for container-nuros-strict profile"
    
    auditctl -w /var/log/audit/ -p rwa -k audit_logs
    
    log_success "Runtime audit rules added"
    
    # Make rules persistent
    RULES_FILE="/etc/audit/rules.d/apparmor.rules"
    
    cat > "$RULES_FILE" << 'EOF'
# Audit rules for NurOS AppArmor container security
# Generated by setup-audit.sh

# Monitor AppArmor kernel interface
-w /sys/kernel/apparmor -p rwa -k apparmor

# Monitor NurOS container profile
-w /etc/apparmor.d/container-nuros-strict -p rwa -k apparmor_profile

# Monitor audit logs
-w /var/log/audit/ -p rwa -k audit_logs

# Monitor AppArmor parser
-w /sbin/apparmor_parser -p x -k apparmor_parser

# Monitor capability changes
-a exit,always -F arch=b64 -S capset -k capability_changes
-a exit,always -F arch=b32 -S capset -k capability_changes
EOF
    
    log_success "Persistent audit rules saved to $RULES_FILE"
    
    # Reload rules
    augenrules --load 2>/dev/null || \
        log_warning "Could not reload audit rules with augenrules"
}

# Verify configuration
verify_configuration() {
    log_info "Verifying audit configuration..."
    
    echo ""
    echo "=== Audit Rules ==="
    auditctl -l | grep -E "(apparmor|audit_logs)" || log_warning "No rules found"
    
    echo ""
    echo "=== Audit Status ==="
    systemctl status auditd --no-pager | head -10
    
    echo ""
    echo "=== Test Audit Log ==="
    # Generate a test log entry
    logger -t auditd-test "Test message from setup-audit.sh"
    log_success "Test log entry created"
}

# Print usage information
print_usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Options:
  -i, --install     Install auditd if not installed
  -s, --skip-install  Skip auditd installation (assume already installed)
  -r, --rules-only  Only configure audit rules (don't install/start service)
  -h, --help        Show this help message

Examples:
  sudo $0                    # Full setup (install + configure)
  sudo $0 --rules-only       # Only configure rules
  sudo $0 --skip-install     # Skip installation, start service and configure

EOF
}

# Main function
main() {
    echo "========================================"
    echo "  NurOS Auditd Setup Script"
    echo "========================================"
    echo ""
    
    # Parse arguments
    INSTALL_AUDITD=true
    RULES_ONLY=false
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            -i|--install)
                INSTALL_AUDITD=true
                shift
                ;;
            -s|--skip-install)
                INSTALL_AUDITD=false
                shift
                ;;
            -r|--rules-only)
                RULES_ONLY=true
                INSTALL_AUDITD=false
                shift
                ;;
            -h|--help)
                print_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                print_usage
                exit 1
                ;;
        esac
    done
    
    # Check root
    check_root
    
    # Check if auditd is installed
    if ! check_auditd_installed; then
        if [ "$INSTALL_AUDITD" = true ]; then
            install_auditd
        else
            log_error "auditd is not installed. Use --install to install it."
            exit 1
        fi
    fi
    
    # Skip service start if rules-only mode
    if [ "$RULES_ONLY" = false ]; then
        start_auditd
    fi
    
    # Configure rules
    configure_audit_rules
    
    # Verify
    verify_configuration
    
    echo ""
    echo "========================================"
    log_success "Auditd setup completed!"
    echo "========================================"
    echo ""
    echo "Next steps:"
    echo "  1. View logs: sudo ausearch -m apparmor_denied -ts today"
    echo "  2. Real-time: sudo tail -f /var/log/audit/audit.log | grep container-nuros-strict"
    echo "  3. Check script: /usr/local/bin/check-apparmor-audit.sh"
    echo ""
}

# Run main function
main "$@"
