# =============================================================================
# Frontend Dockerfile - Production Build
# =============================================================================
# Builds the frontend for GitHub Pages deployment.
# Output: /app/dist directory with static assets.
#
# Usage:
#   docker build -f docker/frontend.Dockerfile -t nuros-frontend .
# =============================================================================

# -----------------------------------------------------------------------------
# Stage 1: Dependencies
# -----------------------------------------------------------------------------
FROM node:22-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install pnpm
RUN corepack enable pnpm && pnpm --version

# Copy package files
COPY listpkgs.nuros.front-end/package.json listpkgs.nuros.front-end/pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile --prefer-offline

# -----------------------------------------------------------------------------
# Stage 2: Build
# -----------------------------------------------------------------------------
FROM deps AS builder

WORKDIR /app

# Copy source code
COPY listpkgs.nuros.front-end/ ./listpkgs.nuros.front-end/

# Set production environment
ENV NODE_ENV=production
ENV CI=true

# Install dependencies
RUN cd listpkgs.nuros.front-end && pnpm install --frozen-lockfile

# Build the frontend
RUN cd listpkgs.nuros.front-end && pnpm build

# Copy repodata.json and sha256 from public to dist (generated by init container)
RUN cd listpkgs.nuros.front-end && \
    if [ -f public/repodata.json ]; then \
        cp public/repodata.json dist/ && \
        echo "✓ Copied repodata.json to dist"; \
    else \
        echo "✗ No repodata.json found in public"; \
    fi && \
    if [ -f public/repodata.json.sha256 ]; then \
        cp public/repodata.json.sha256 dist/ && \
        echo "✓ Copied repodata.json.sha256 to dist"; \
    else \
        echo "✗ No repodata.json.sha256 found in public"; \
    fi || true

# -----------------------------------------------------------------------------
# Stage 3: Development Preview (nginx for local testing)
# -----------------------------------------------------------------------------
FROM nginx:alpine AS preview

LABEL maintainer="NurOS Development Team"
LABEL description="Local preview of built frontend"

# Copy custom nginx config (context is project root)
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copy built assets from builder stage
COPY --from=builder /app/listpkgs.nuros.front-end/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost/ || exit 1

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
